### ISSUE TITLE
GetInput

### ISSUE THREAD

**Issue by streetgt** [Chaser324/LZF#1]
Hello, any change of getting GetInput method snippet?

greetings

**Comment by Chaser324** [comment]
I'm unsure of what you mean. Can you clarify a bit more?

**Comment by streetgt** [comment]
The example you specify on readme.md.

// GetInput is some method that fills inputBuffer and returns inputBuffer.Length.
while(GetInput(ref inputBuffer) > 0)

**Comment by Chaser324** [comment]
It's just an example, so it's intentionally vague and generic. The only important point is that `inputBuffer` contains what you want to compress. How you fill `inputBuffer` depend entirely on what sort of data you want to compress. It doesn't need to be in a while loop or from a separate function call at all.
